#                      **Working with Numpy for Mathemetical Opertion**


In [4]:
import numpy as np
a = np.array([[1,4],[1,4],[1,2]])  # here we hav to write like ([[Row-1],[Row-2],[Row-3]])
print(a)
print(type(a))         # printing type of a  . It's a inbuilt method.
print(a.shape)         # It's  not a method ,It's a Attribute .

# If a matix dimention is 3X5 the its shape will be (3,5) (number of row , number of column).

print(a[2][0])  # Here we are printing any element of matix a , so the method is a[index of row][index of column] . Note index starts from 0 .

[[1 4]
 [1 4]
 [1 2]]
<class 'numpy.ndarray'>
(3, 2)
1


In [37]:
# Creats Zeros ,Ones , Custom array
a = np.zeros((3,3)) #here we using zeros inbuilt method to make Zeros array and we passing (3,3) dimention to making into matix
print(a)
# <---------------------------------------------->
print("")
print("<---------------------->")
print("")
# <---------------------------------------------->
b = np.ones((2,3)) #here we using zeros inbuilt method to make Zeros array and we passing (3,3) dimention to making into matix
print(b)
# <---------------------------------------------->
print("")
print("<---------------------->")
print("")
# <---------------------------------------------->
# Array of Some Constent
d = np.full((3,5), 6)
print(d)
# <---------------------------------------------->
print("")
print("<---------------------->")
print("")
# <---------------------------------------------->
# Identity Matrix - size/square matrix
d = np.eye(4)
print(d)
# <---------------------------------------------->
print("")
print("<---------------------->")
print("")
# <---------------------------------------------->
#Random matrix
randomMatrix = np.random.random((4,4))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

<---------------------->

[[1. 1. 1.]
 [1. 1. 1.]]

<---------------------->

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]

<---------------------->

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

<---------------------->

[[0.84988008 0.67869294 0.85017664 0.6027332 ]
 [0.6001569  0.2593942  0.4436731  0.03843797]
 [0.21925434 0.12796811 0.699268   0.29197592]
 [0.40797307 0.49254666 0.52325595 0.89643568]]


In [56]:
print(randomMatrix[1:3,3])  #How to do slicing here let's see.......method 1 [no. of rows , no of column]
                            # method 2 [no of rows start : no of rows end , no of column start : no of column end ]
                            # if we don't give any value [:,5] its means all rows and 5th column
print(randomMatrix[1,2:])

[0.03843797 0.29197592]
[0.6001569  0.2593942  0.4436731  0.03843797]


In [60]:
# Set some rows and column with any values
z = np.zeros((3,3))
print(z)
z[1,:] = 5
z[ :,-1]=7
print(z)
# Data type
print(z.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]
float64


In [62]:
# if we want to change datatype 

z = np.zeros((3,3) , dtype = np.int64)
print(z)
z[1,:] = 5
z[ :,-1]=7
print(z)
# Data type
print(z.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]
int64


In [69]:
# Mathematical Operations
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#Element wise addition
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [70]:
# Matrix multiplication / Dot product
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [105]:
# Multiplication(Dot product) of vectors => Scalar 
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [106]:
print(a)

[1 2 3 4]


In [107]:
print(sum(a))

10


In [108]:
print(x)

[[1 2]
 [3 4]]


In [109]:
print(np.sum(x))
print(np.sum(x,axis = 0)) # axis is optional , if we want to sum row by then we axis = 1 , if we want to sum column by then axis = 0

10
[4 6]


In [111]:
# stacking of array 
print(a)
b = b*2
print(b)

[1 2 3 4]
[ 4  8 12 16]


In [112]:
a = np.stack((a,b),axis = 0)

In [114]:
# Reshape a numpy Array
print(a)
a = a.reshape((4,2))  # reshape is a method if we don't know column and knwn row them we can pass (4,-1) 
                      # && if we know clumn and don't row number of row then we can pass (-1,4) argument . 
                      # It automatically recognize no of row or column if they are nt menton properly
print(a)

[[ 1  2  3  4]
 [ 4  8 12 16]]
[[ 1  2]
 [ 3  4]
 [ 4  8]
 [12 16]]


# Some More Numpy Function-Statics
---
⚛ min , max
⚛ mean
⚛ median
⚛ average
⚛ variance
⚛ standard devidation


In [ ]:
a = np.array([1,2,3,4,5],[9,6,3,8,5])
print(a)
print(np.min(a))

# Specific axis for the direction in case of multidim array 
print(np.min(a,axis=0))
print(np.min(a,axis=1))

# Mean , average all the elements 

b = np.array([5,6,9,7,8])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis = 0))

In [21]:
c = np.array([1,5,4,2,0])
print(np.median(c))
 
# Mean vs Average is weighted
print(np.mean(c))

w = np.array([1,2,3,4,5])
print(np.average(c, weights=w))

2.0
2.4
2.066666666666667


In [22]:
# Standard Deviation 
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

# Inbuilt function
dev = np.std(c)
print(dev)

1.854723699099141
1.854723699099141


# &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; **Numpy Random Module**
---
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;▶ rand : Random values in a given shape.\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;▶ randn: Return a sample (or samples) from the "standard normal" distribution.\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;▶ randint: Return random integers from low (inclusive) to high (exclusive).\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;▶ random: Return random floats in the half-open interval [0.0, 1.0)\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;▶ choice: Generates a random sample from a given 1-D array \
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;▶ Shuffle: Shuffles the contents of a sequence



In [12]:
a = np.arange(10) # if we want that it's start from any other number then we can simply add that number
                   # ex:- a = np.arange(10) + 5  result :- [ 5  6  7  8  9 10 11 12 13 14]
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
np.random.shuffle(a) # It will shuffle 
print(a)

[6 8 7 1 5 4 0 9 3 2]


In [19]:
# Return values from a Standard Normal Distributions

a = np.random.rand(2,3) # If we want to generate random array
print(a)

a = np.random.randint(5,10,2) # Basically it take range as first two input and third one how many elements we want in array
print(a)

# Randomly pick one element 
elements = np.random.choice([1,2,3,4,5,6,7,8,9])
print(elements)

[[0.8490609  0.55865691 0.63423194]
 [0.05298663 0.13593589 0.21178592]]
[8 6]
2
